name: CI Pipeline

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      # TASK 2: Code Linting Step
      - name: Run Code Linting
        run: npx eslint src/**

      # TASK 3: Unit Testing Step
      - name: Run Unit Tests
        run: npm test
